services:
  - type: web
    name: simple-book-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: TOKEN_SECRET
        sync: false
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: ADMIN_EMAIL
        sync: false
